[package]
name = "binary_derive"
version = "0.2.0"
authors = ["Daniel Lehmann <mail@dlehmann.eu>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.12", features = ["extra-traits"] }
quote = "0.4"